######post#### https://sr-portal-graphql-api.vercel.app
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "query GetPosts($l imit: Int!, $cursor: Int) { posts(data: { limit: $limit, cursor: $cursor }) { status message data{posts{ id title body userId createdAt updatedAt arrestLogId imageUrls likes{ id isActive userId postId } } cursor hasNextPage}}}",
  "variables": { "limit": 5, "cursor": null }
}

#####
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "query GetPost($id: Int!) { post(id: $id) { id title body userId createdAt updatedAt arrestLogId } }",
  "variables": {
    "id": 1
  }
}
#####
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "mutation CreatePost($data: CreatePostInput!) { createPost(data: $data) { id title body userId createdAt updatedAt arrestLogId } }",
  "variables": {
    "data": {
      "title": "Test Post 9",
      "body": "This is a test post body.",
      "userId": "cmghh4hul0000mnarlu1tlyqv",
      "arrestLogId": null
    }
  }
}

###### update a post
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "mutation UpdatePost($id: ID!, $data: UpdatePostInput!) { updatePost(id: $id, data: $data) { id title body updatedAt } }",
  "variables": {
    "id": 2,
    "data": {
      "title": "Updated Title",
      "body": "Updated body content"
    }
  }
}
######
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "mutation DeletePost($id: ID!) { deletePost(id: $id) { id } }",
  "variables": {
    "id": 2
  }
}