###### user
POST http://localhost:3000/api/graphql
Content-Type: application/json
Authorization: Bearer YOUR_JWT_HERE

{
  "query": "mutation CreatePaymentIntent($data: CreatePaymentIntentInput) { createPaymentIntent(data: $data) { data { clientSecret} message status } }",
  "variables": {
    "data": {
      "amount": 5000
    }
  }
}
######
