//https://sr-portal-graphql-api.vercel.app
//http://localhost:3000/api/graphql

######user
POST http://localhost:3000/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NTc0NjA3MTcsImV4cCI6MTc1NzQ2NDMxN30.3p62jIwPKVYwQUJwSSt5Ahh0FxrX1KmouL4yzaCnaHI

{
  "query": "query { users { id firstname lastname email username createdAt updatedAt password } }"
}
######
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "mutation ResendVerificationEmail($email: String!) { resendVerificationEmail(email: $email) }",
  "variables": {
    "email": "johns.doe@example.com"
  }
}
######
POST http://localhost:3000/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NTc0NjA3MTcsImV4cCI6MTc1NzQ2NDMxN30.3p62jIwPKVYwQUJwSSt5Ahh0FxrX1KmouL4yzaCnaHI


{
  "query": "mutation { registerUser(data: { firstname: \"Christian\", lastname: \"Esperon\", username: \"cesperon\", email: \"cesperon4@gmail.com\", password: \"test123\", role:USER }) }"
}

######
######
POST http://localhost:3000/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

{
  "query": "mutation VerifyEmail($token: Token!) { verifyEmail(token: $token) }",
  "variables": {
    "token": "311e2888a9f9a57b861b53f4d5845c03e85a65e31437696d89b60dad5679dfb7"
  }
}


######
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "query GetUser($id: ID!) { user(id: $id) { id firstname lastname email username createdAt updatedAt } }",
  "variables": {
    "id": "cmag3cjpx0000i7tceu14nxhg"
  }
}
######
POST http://localhost:3000/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NTc0NjA3MTcsImV4cCI6MTc1NzQ2NDMxN30.3p62jIwPKVYwQUJwSSt5Ahh0FxrX1KmouL4yzaCnaHI


{
  "query": "mutation { createUser(data: { firstname: \"John\", lastname: \"Doe\", username: \"johndoes\", email: \"johns.doe@example.com\", password: \"test123\", role:USER }) { id firstname lastname username email createdAt updatedAt } }"
}

######
POST https://sr-portal-graphql-api.vercel.app/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NTc0NjA3MTcsImV4cCI6MTc1NzQ2NDMxN30.3p62jIwPKVYwQUJwSSt5Ahh0FxrX1KmouL4yzaCnaHI


{
  "query": "mutation { upsertUser(data: { firstname: \"Johss\", lastname: \"Does\", email: \"johnss.does@example.com\"}) { token } }"
}

######
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "mutation { updateUser(id: \"cmag3cjpx0000i7tceu14nxhg\", data: { firstname: \"Christian\", lastname: \"Esperon\" }) { id firstname lastname email username createdAt updatedAt } }"
}
######
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "mutation { deleteUser(id: \"cmfr3cevw0000mn50ft11ky9f\") { id firstname lastname email username createdAt updatedAt } }"
}

####
POST http://localhost:3000/api/graphql
Content-Type: application/json


{
  "query": "mutation {login(data:{email: \"johns.doe@example.com\", password: \"test123\"}){user{id role} token}}"

}
####
POST https://sr-portal-graphql-api.vercel.app/api/graphql
Content-Type: application/json

{
  "query": "mutation {logout}"

}

####
POST http://localhost:3000/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWFyZGg5ZnIwMDAwaTdldHVhZW5tZ2xhIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc0MzQ3NDgsImV4cCI6MTc0NzQzODM0OH0.-pSv_2mS6U1_DA45ZHVhlJO5oFzsbt4NtdDSo-GopHg

{
  "query": "query {me{id firstname lastname email password username createdAt updatedAt}}"

}

####
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query" : "mutation {loginGuest{token}}"
}



