//https://sr-portal-graphql-api.vercel.app
//http://localhost:3000/api/graphql

######user
POST https://sr-portal-graphql-api.vercel.app/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiR1VFU1QiLCJpYXQiOjE3NjM2OTc5NTQsImV4cCI6MTc2MzcwMTU1NH0.g2dbpaBb3L3pH79rP8Hn6D6Ig-rSzXbXoAYAFpYz69E

{
  "query": "query { users { data { id firstname lastname email username createdAt updatedAt password emailVerified } message status } }"
}
######user
GET https://services2.arcgis.com/BhTdzxiJkq4oXsPh/arcgis/rest/services/Santa Rosa Police Pursuits/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json&orderByFields=
Content-Type: application/json


######
######
POST http://localhost:3000/api/graphql
Content-Type: application/json
Authorization: Bearer YOUR_TOKEN

{
  "query": "query GetUser($id: ID!, $limit: Int!, $cursor: Int) { user(id: $id) { data { id firstname lastname email username createdAt updatedAt posts(data: { limit: $limit, cursor: $cursor }) { data { data { id title createdAt userId } hasNextPage cursor } } } } }",
  "variables": {
    "id": "cmj8030tx000087mnvo2xnk5q",
    "limit": 24,
    "cursor": null
  }
}
######
POST http://localhost:3000/api/graphql
Content-Type: application/json
Authorization: Bearer YOUR_TOKEN

{
  "query": "query GetUserComments($id: ID!, $limit: Int!, $cursor: Int) { user(id: $id) { status message data { id firstname lastname email username createdAt updatedAt comments(data: { limit: $limit, cursor: $cursor }) { data { data { id body createdAt post { title } } hasNextPage cursor } message status } } } }",
  "variables": {
    "id": "cmj8030tx000087mnvo2xnk5q",
    "limit": 5,
    "cursor": null
  }
}
####
######
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "query GetUserLikedPosts($id: ID!, $limit: Int!, $cursor: Int) { user(id: $id) { status message data { id firstname lastname email username createdAt updatedAt likedPosts(data: { limit: $limit, cursor: $cursor }) { data { data { id userId  post{ id } } hasNextPage cursor } message status } } } }",
  "variables": {
    "id": "cmj8030tx000087mnvo2xnk5q",
    "limit": 5,
    "cursor": null
  }
}
####
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "mutation ResendVerificationEmail($email: String!) { resendVerificationEmail(email: $email) }",
  "variables": {
    "email": "johns.doe@example.com"
  }
}
######
POST https://sr-portal-graphql-api.vercel.app/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NTc0NjA3MTcsImV4cCI6MTc1NzQ2NDMxN30.3p62jIwPKVYwQUJwSSt5Ahh0FxrX1KmouL4yzaCnaHI


{
  "query": "mutation { registerUser(data: { firstname: \"Pamela\", lastname: \"Tiongson\", username: \"ptiongson\", email: \"ptiongson@gmail.com\", password: \"test123\", role:USER }) }"
}

######
######
POST https://sr-portal-graphql-api.vercel.app/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

{
  "query": "mutation VerifyEmail($token: Token!) { verifyEmail(token: $token) }",
  "variables": {
    "token": "23c0bd8ea82e2d05b2cd4dd7ab5a468327405ff804acaf36990d3e9082e060b7"
  }
}


######
POST http://localhost:3000/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWhtbnFzb2cwMDAwanMwZjYyMGd2cGJjIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NjM2NTY1NjUsImV4cCI6MTc2MzY2MDE2NX0.eGdUNcZeiWrQuJbU1Es3dAV2bFUxSvEPWO6jUJbKLVA

{
  "query": "query GetUser($id: ID!) { user(id: $id) { data { id firstname lastname email username createdAt updatedAt}  } }",
  "variables": {
    "id": "cmj8030tx000087mnvo2xnk5q"
  }
}
######
POST http://localhost:3000/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NTc0NjA3MTcsImV4cCI6MTc1NzQ2NDMxN30.3p62jIwPKVYwQUJwSSt5Ahh0FxrX1KmouL4yzaCnaHI


{
  "query": "mutation { createUser(data: { firstname: \"John\", lastname: \"Doe\", username: \"johndoes\", email: \"johns.doe@example.com\", password: \"test123\", role:USER }) { id firstname lastname username email createdAt updatedAt } }"
}

######
POST http://localhost:3000/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NTc0NjA3MTcsImV4cCI6MTc1NzQ2NDMxN30.3p62jIwPKVYwQUJwSSt5Ahh0FxrX1KmouL4yzaCnaHI


{
  "query": "mutation { upsertUser(data: { firstname: \"Johss\", lastname: \"Does\", email: \"johnss.does@example.com\"}) { data {user {id} token } message } }"
}

######
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "mutation { updateUser(id: \"cmhmnqsog0000js0f620gvpbc\", data: { firstname: \"Christian\", lastname: \"Esperon\", emailVerified: \"true\"}) { id firstname lastname email username createdAt updatedAt } }"
}
######
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "mutation { deleteUser(id: \"cmfrzrj7t0009mnu50zskieil\") { id firstname lastname email username createdAt updatedAt } }"
}

####
POST http://localhost:3000/api/graphql
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NjIzODc2MDUsImV4cCI6MTc2MjM5MTIwNX0.26hkNLuWmJiin1yxFMhgQNe-qMsKPgoCUdfONwgtGrg


{
  "query": "mutation {login(data:{email: \"cesperon4@gmail.com\", password: \"test123\"}){user{id role} token}}"

}
####
POST https://sr-portal-graphql-api.vercel.app/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NjIzODc2MDUsImV4cCI6MTc2MjM5MTIwNX0.26hkNLuWmJiin1yxFMhgQNe-qMsKPgoCUdfONwgtGrg

{
  "query": "mutation {logout}"

}

####
POST http://localhost:3000/api/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWFyZGg5ZnIwMDAwaTdldHVhZW5tZ2xhIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc0MzQ3NDgsImV4cCI6MTc0NzQzODM0OH0.-pSv_2mS6U1_DA45ZHVhlJO5oFzsbt4NtdDSo-GopHg

{
  "query": "query {me{id firstname lastname email password username createdAt updatedAt}}"

}

####
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query" : "mutation {loginGuest{token}}"
}



